#!/usr/bin/env python3
"""Generate the 1000-account username/password/role pool for the vulnerable
range, from a jsmith.txt-style username list. Deterministic (first N names,
fixed role-index assignment) so re-runs produce the same file if it's ever
regenerated by hand; normal re-runs are skipped entirely via Ansible's
`creates:` guard, since passwords must stay stable once created in AD.

Usage: generate_pool_accounts.py <jsmith.txt> <output.csv> [pool_size]
"""
import csv
import secrets
import string
import sys

POOL_SIZE_DEFAULT = 1000
RESERVED_PASSWORD = "password"

# Fixed index -> role assignment. Order doesn't matter beyond being stable;
# what matters is every role lands on a distinct pool username.
SPECIAL_ROLES = [
    "writedacl_target",
    "genericwrite_target",
    "forcechangepw_target",
    "writeowner_target",
    "netlogon_creds",
    "desc_field_pw",
    "asreproast",
    "smbshare_creds",
] + [f"weakcreds_{i}" for i in range(1, 11)]

# Fixed (not randomly generated) passwords for roles where the design
# specifies an exact value.
FIXED_PASSWORDS = {
    "asreproast": "princess",
    "weakcreds_1": "Summer2026",
    "weakcreds_2": "Password1",
    "weakcreds_3": "Welcome123",
    "weakcreds_4": "Qwerty123!",
    "weakcreds_5": "Winter2025",
    "weakcreds_6": "Letmein123",
    "weakcreds_7": "Football1",
    "weakcreds_8": "Baseball1",
    "weakcreds_9": "Admin@123",
    "weakcreds_10": "ChangeMe1",
}

SYMBOLS = "!@#$%^&*-_="


def generate_password(length=14):
    groups = [string.ascii_uppercase, string.ascii_lowercase, string.digits, SYMBOLS]
    alphabet = string.ascii_letters + string.digits + SYMBOLS
    while True:
        chars = [secrets.choice(g) for g in groups]
        chars += [secrets.choice(alphabet) for _ in range(length - len(chars))]
        secrets.SystemRandom().shuffle(chars)
        pw = "".join(chars)
        if pw.lower() != RESERVED_PASSWORD:
            return pw


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <jsmith.txt> <output.csv> [pool_size]", file=sys.stderr)
        sys.exit(1)

    src_path, out_path = sys.argv[1], sys.argv[2]
    pool_size = int(sys.argv[3]) if len(sys.argv) > 3 else POOL_SIZE_DEFAULT

    with open(src_path, encoding="utf-8") as f:
        names = [line.strip() for line in f if line.strip()]

    seen = set()
    unique_names = []
    for name in names:
        if name not in seen:
            seen.add(name)
            unique_names.append(name)
        if len(unique_names) >= pool_size:
            break

    if len(unique_names) < pool_size:
        print(f"WARNING: only {len(unique_names)} unique usernames available, wanted {pool_size}", file=sys.stderr)

    rows = []
    for i, username in enumerate(unique_names):
        role = SPECIAL_ROLES[i] if i < len(SPECIAL_ROLES) else ""
        password = FIXED_PASSWORDS.get(role, generate_password())
        rows.append((username, password, role))

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["username", "password", "role"])
        writer.writerows(rows)

    print(f"Wrote {len(rows)} accounts to {out_path} ({len(SPECIAL_ROLES)} special roles assigned)")


if __name__ == "__main__":
    main()
