all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_cyberrange
  children:
    proxmox:
      hosts:
        proxmox-host:
          ansible_host: 192.168.192.150
          ansible_user: root
    linux_vms:
      hosts: {}
    windows_vms:
      hosts: {}
